import { Router } from 'express';
import authRoutes from './auth.routes';
import dashboardRoutes from './dashboard.routes';
import userRoutes from './user.routes';
import roleRoutes from './role.routes';
import inventoryRoutes from './inventory.routes';
import salesRoutes from './sales.routes';
import salesOrderRoutes from './salesOrder.routes';
import salesReturnRoutes from './salesReturn.routes';
import purchaseRoutes from './purchase.routes';
import purchaseReturnRoutes from './purchaseReturn.routes';
import customerRoutes from './customer.routes';
import bookingRoutes from './booking.routes';
import paymentRoutes from './payment.routes';
import masterRoutes from './master.routes';
import reportRoutes from './report.routes';
import discountRoutes from './discount.routes';
import voucherRoutes from './voucher.routes';
import commissionRoutes from './commission.routes';
import tallyRoutes from './tally.routes';
import healthRoutes from './health.routes';
import defectiveStockRoutes from './defectiveStock.routes';
import rpcRoutes from './rpc.routes';
import storageRoutes from './storage.routes';
import salesmanRoutes from './salesman.routes';
import creditCouponRoutes from './creditCoupon.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/sales', salesRoutes);
router.use('/sales-orders', salesOrderRoutes);
router.use('/sales-returns', salesReturnRoutes);
router.use('/purchases', purchaseRoutes);
router.use('/purchase-returns', purchaseReturnRoutes);
router.use('/customers', customerRoutes);
router.use('/bookings', bookingRoutes);
router.use('/e-bookings', bookingRoutes);
router.use('/payments', paymentRoutes);
router.use('/payment-receipts', paymentRoutes);
router.use('/payment-receipt-items', paymentRoutes);
router.use('/masters', masterRoutes);
router.use('/reports', reportRoutes);
router.use('/discounts', discountRoutes);
router.use('/vouchers', voucherRoutes);
router.use('/commission', commissionRoutes);
router.use('/tally', tallyRoutes);
router.use('/health', healthRoutes);
router.use('/defective-stock', defectiveStockRoutes);
router.use('/rpc', rpcRoutes);
router.use('/storage', storageRoutes);
router.use('/salesmen', salesmanRoutes);
router.use('/credit-coupons', creditCouponRoutes);

export default router;
