import * as http from 'http';

const BASE_URL = 'http://localhost:3000/api';
let authToken = '';

// Helper function to make HTTP requests
async function makeRequest(
  method: string,
  endpoint: string,
  body?: any,
  useAuth: boolean = true
) {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };
  
  if (useAuth && authToken) {
    headers['Authorization'] = `Bearer ${authToken}`;
  }

  try {
    const response = await fetch(`${BASE_URL}${endpoint}`, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    const data = await response.json().catch(() => null);
    
    return {
      status: response.status,
      ok: response.ok,
      data
    };
  } catch (error: any) {
    return {
      status: 500,
      ok: false,
      error: error.message
    };
  }
}

// Simple test runner
async function runTest(name: string, testFn: () => Promise<boolean>) {
  process.stdout.write(`Testing ${name}... `);
  try {
    const success = await testFn();
    if (success) {
      console.log('✅ PASSED');
    } else {
      console.log('❌ FAILED');
    }
    return success;
  } catch (err: any) {
    console.log(`❌ FAILED with error: ${err.message}`);
    return false;
  }
}

async function runAllTests() {
  console.log('🚀 Starting Backend API Integration Tests\n');
  
  // 1. Test Authentication
  const authPassed = await runTest('POST /api/auth/login', async () => {
    // Assuming 9999999999 is the default admin generated by standard seeders
    const res = await makeRequest('POST', '/auth/login', {
      mobile: '9999999999',
      password: 'ant-admin@123'
    }, false);
    
    if (res.ok && res.data?.data?.token) {
      authToken = res.data.data.token;
      return true;
    }
    console.log(`\n   Response: ${JSON.stringify(res.data)}`);
    return false;
  });

  if (!authPassed) {
    console.log('\n🛑 Stopping tests because authentication failed. Check backend credentials!');
    return;
  }

  // 2. Test Get Profile
  await runTest('GET /api/auth/me', async () => {
    const res = await makeRequest('GET', '/auth/me');
    return res.ok && res.data?.data?.mobile === '9999999999';
  });

  // 3. Test Cities Master
  let testCityId = '';
  await runTest('POST /api/masters/cities', async () => {
    const res = await makeRequest('POST', '/masters/cities', {
      city_code: `TEST${Math.floor(Math.random() * 1000)}`,
      name: 'Test City',
      state: 'Test State',
      active: true
    });
    if (res.ok) {
      testCityId = res.data?.data?.id;
      return true;
    }
    return false;
  });

  // 4. Test Vendors Master
  let testVendorId = '';
  await runTest('POST /api/masters/vendors', async () => {
    const res = await makeRequest('POST', '/masters/vendors', {
      city_id: testCityId,
      vendor_code: `V${Math.floor(Math.random() * 1000)}`,
      name: 'Test Vendor',
      address: '123 Test Street'
    });
    if (res.ok) {
      testVendorId = res.data?.data?.id;
      return true;
    }
    return false;
  });

  // 5. Test Product Groups Master
  let testGroupId = '';
  await runTest('POST /api/masters/product-groups', async () => {
    const res = await makeRequest('POST', '/masters/product-groups', {
      group_code: `PG${Math.floor(Math.random() * 1000)}`,
      name: 'Test Group',
      hsn_code: '1234',
      tax_percentage: 18,
      is_fabric: false
    });
    if (res.ok) {
      testGroupId = res.data?.data?.id;
      return true;
    }
    return false;
  });

  // 6. Test Product Master
  let testProductMasterId = '';
  await runTest('POST /api/masters/product-masters', async () => {
    const res = await makeRequest('POST', '/masters/product-masters', {
      group_id: testGroupId,
      item_name: 'Test Product',
      design_number: `D${Math.floor(Math.random() * 1000)}`,
      vendor_id: testVendorId
    });
    if (res.ok) {
      testProductMasterId = res.data?.data?.id;
      return true;
    }
    return false;
  });

  // 7. Test Inventory
  let testInventoryId = '';
  await runTest('POST /api/inventory', async () => {
    const res = await makeRequest('POST', '/inventory', {
      product_master_id: testProductMasterId,
      vendor_id: testVendorId,
      color_id: null,
      size_id: null,
      barcode: `TESTB${Math.floor(Math.random() * 10000)}`,
      cost_price: 1000,
      mrp: 2000,
      quantity: 10
    });
    if (res.ok) {
      testInventoryId = res.data?.data?.id || res.data?.data?.[0]?.id;
      return true;
    }
    console.log(`\n   Response: ${JSON.stringify(res.data)}`);
    return false;
  });

  // 8. Test Customers
  let testCustomerId = '';
  await runTest('POST /api/customers', async () => {
    const res = await makeRequest('POST', '/customers', {
      mobile: `9${Math.floor(Math.random() * 1000000000).toString().padEnd(9, '0')}`,
      name: 'Test Customer'
    });
    if (res.ok) {
      testCustomerId = res.data?.data?.id;
      return true;
    }
    return false;
  });

  // 9. Fetch All Inventory
  await runTest('GET /api/inventory', async () => {
    const res = await makeRequest('GET', '/inventory');
    return res.ok && Array.isArray(res.data?.data);
  });

  // 10. Fetch All Customers
  await runTest('GET /api/customers', async () => {
    const res = await makeRequest('GET', '/customers');
    return res.ok && Array.isArray(res.data?.data);
  });

  console.log('\n🎉 Finished testing API endpoints!');
}

runAllTests().catch(console.error);
